### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MisterKangaroo**
Made some slight changes to clarify (esp. for new users) how to implement the SVG code in a p5.js project.

### CODE REVIEW

**Comment by MisterKangaroo** [comment]
Thanks for your hard work @zenozeng @dannewoo .
Hope these slight changes in the Readme will help new users to get a easy entrance.

**Comment by zenozeng** [comment]
Hi @MisterKangaroo , thanks for your pull request. It's helpful for new users.

`https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/p5.js` and `https://unpkg.com/p5@1.3.1/lib/p5.js` should be identical. 
So it's not necessary to comment. Adding the following line should be enough:
```html
<script src="https://unpkg.com/p5.js-svg@1.0.7"></script>
```

Could you modify your pull request?

**Comment by MisterKangaroo** [comment]
> Could you modify your pull request?

Thanks for your reply. Modified as requested...

**Comment by MisterKangaroo** [comment]
> So it's not necessary to comment. Adding the following line should be enough:
> 
> ```
> <script src="https://unpkg.com/p5.js-svg@1.0.7"></script>
> ```

Shouldn't it be the 1.0.8 instead?

> ```
> <script src="https://unpkg.com/p5.js-svg@1.0.8"></script>
> ```

**Comment by zenozeng** [comment]
Thanks @MisterKangaroo !

**Pull request merged**
